#!/bin/bash
# Quick display/audio reset - same as v1

echo -e ">>>> TV resolution to 1600x900"
xrandr --output HDMI-1 --primary --mode 1600x900

echo -e "\n>>>> Disable internal monitor"
xrandr --output eDP-1 --off

echo -e "\n>>>> Set screen timeout to never"
gsettings set org.gnome.desktop.session idle-delay 0

echo -e "\n>>>> Set HDMI audio"
# Ubuntu 24.04 uses PipeWire - use pactl (pacmd is deprecated)
HDMI_SINK=$(pactl list short sinks | grep -i hdmi | head -1 | awk '{print $2}')
if [ -n "$HDMI_SINK" ]; then
  pactl set-default-sink "$HDMI_SINK"
  echo "HDMI audio set: $HDMI_SINK"
else
  echo "Warning: No HDMI sink found"
fi

echo -e "\n>>>> Done"
